# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classrom',
            new_name='Classroom',
        ),
    ]
