# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='datetime',
        ),
    ]
